window.PadInputColors=(function(){
    const colors=[
        {
            id:1,
            color:"red",
            isChosen:false,
        },
        {
            id:2,
            color:"orange",
            isChosen:false,
        },
        {
            id:3,
            color:"yellow",
            isChosen:false,
        },
        {
            id:4,
            color:"green",
            isChosen:false,
        },
        {
            id:5,
            color:"blue",
            isChosen:false,
        },
        {
            id:6,
            color:"violet",
            isChosen:false,
        },
        {
            id:7,
            color:"while",
            isChosen:false,
        },
        {
            id:8,
            color:"brown",
            isChosen:false,
        },
    ];
    return {colors:colors};
}());